# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

plugin 'cocoapods-embed-flutter'

target 'app_ios' do
  use_frameworks!
  pub 'my_flutter_offshore', :git => 'https://github.pactual.net/portal-offshore/flutter-module-ios', :branch => 'try/2'
  # pub 'my_flutter', :path => '../my_flutter'
end
