# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

plugin 'cocoapods-embed-flutter'

target 'app_ios2' do
  use_frameworks!
  pub 'my_flutter', :git => 'https://github.com/MaatheusGois/poc-flutter-ios', :branch => 'master'
  # pub 'my_flutter', :path => '../my_flutter'
end
